import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { useGameStore } from '@/stores/useGameStore';
import { useLanguage } from '@/app/LanguageContext';
import { MdClose, MdHistory, MdPlayArrow, MdDelete, MdContentCopy, MdCheck } from 'react-icons/md';

interface SavesScreenProps {
  onBack: () => void;
}

const SavesScreen: React.FC<SavesScreenProps> = ({ onBack }) => {
  const { t } = useLanguage();
  const { saveHistory, loadSave, deleteSave } = useGameStore();
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const handleLoad = (id: string) => {
    loadSave(id);
  };

  const copyLogs = (save: any) => {
    if (!save.state.log) return;
    
    // 1. En-tête stylisé
    const reportHeader = `╔═══════════════════════════════════════════╗\n` +
                         `  ⚽ MATCH REPORT: ${save.state.player.teamName.toUpperCase()} vs ${save.state.opponent.teamName.toUpperCase()}\n` +
                         `╚═══════════════════════════════════════════╝\n` +
                         `📅 Date: ${formatDate(save.timestamp)}\n` +
                         `🏆 Final Result: ${save.state.player.score} - ${save.state.opponent.score}\n` +
                         `----------------------------------------------\n\n`;

    // 2. Narration Chronologique (Traduction récursive)
    const formattedLogs = save.state.log
      .map((l: any) => {
          const translatedParams = { ...l.params };
          if (l.params) {
              Object.keys(l.params).forEach(k => {
                  const val = l.params[k];
                  if (typeof val === 'string' && val.startsWith('logs.')) {
                      translatedParams[k] = t(val);
                  }
              });
          }
          let line = t(l.key, translatedParams);
          // Si c'est un log d'IA, on ajoute un marqueur technique pour l'analyse
          if (l.key.includes('ai_')) {
              line = `[BOT LOG] ${line}`;
          }
          return line;
      })
      .reverse()
      .join('\n');

    // 3. Bloc technique pour analyse (Optionnel mais pro)
    const techData = `\n\n----------------------------------------------\n` +
                     `📊 ANALYTICS DATA (For Tactical Review)\n` +
                     `Match ID: ${save.state.id}\n` +
                     `Total Goals: ${save.state.goals.length}\n` +
                     `Remaining Deck (P/O): ${save.state.player.deck.length}/${save.state.opponent.deck.length}\n` +
                     `----------------------------------------------\n` +
                     `🏁 End of Report - Generated by 1863 AI Engine ⚽`;

    const finalReport = reportHeader + formattedLogs + techData;

    const textArea = document.createElement("textarea");
    textArea.value = finalReport;
    document.body.appendChild(textArea);
    textArea.select();
    
    try {
      const successful = document.execCommand('copy');
      if (successful) {
        setCopiedId(save.id);
        setTimeout(() => setCopiedId(null), 2000);
      }
    } catch (err) {
      console.error('Match Report: Unable to copy', err);
    }
    document.body.removeChild(textArea);
  };

  const formatDate = (timestamp: number) => {
    return new Date(timestamp).toLocaleString();
  };

  return (
    <motion.div 
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        exit={{ opacity: 0 }}
        className="w-full h-full bg-[#050505] text-white flex flex-col relative overflow-hidden"
    >
      <div className="absolute inset-0 opacity-10 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')] pointer-events-none"></div>

      <div className="flex justify-between items-center p-6 bg-black/40 backdrop-blur-2xl border-b border-white/10 shadow-xl z-10">
        <div className="flex flex-col">
            <span className="text-[9px] font-black text-[#afff34] uppercase tracking-[4px] mb-1">STADIUM VAULT</span>
            <h1 className="text-2xl font-black uppercase tracking-tighter text-white flex items-center gap-2">
                <MdHistory className="text-[#afff34]" />
                {t('menu.past_matches')}
            </h1>
        </div>
        <button onClick={onBack} className="w-10 h-10 rounded-full bg-white/5 border border-white/10 flex items-center justify-center hover:bg-white/10 transition-all active:scale-90">
            <MdClose size={24} className="text-white/70" />
        </button>
      </div>

      <div className="flex-1 overflow-y-auto p-6 custom-scrollbar relative z-10">
        {saveHistory.length === 0 ? (
            <div className="h-full flex flex-col items-center justify-center opacity-30 gap-4">
                <MdHistory size={64} />
                <p className="font-black uppercase tracking-widest text-sm">{t('game.no_saves')}</p>
            </div>
        ) : (
            <div className="grid grid-cols-1 gap-4 pb-20">
                <AnimatePresence>
                    {saveHistory.map((save, i) => (
                        <motion.div
                            key={save.id}
                            initial={{ opacity: 0, x: -20 }}
                            animate={{ opacity: 1, x: 0 }}
                            exit={{ opacity: 0, scale: 0.95 }}
                            transition={{ delay: i * 0.05 }}
                            className="bg-white/5 border border-white/10 rounded-2xl p-5 flex flex-col gap-4 group hover:bg-white/10 hover:border-[#afff34]/30 transition-all shadow-xl"
                        >
                            <div className="flex items-center justify-between">
                                <div className="flex flex-col gap-1">
                                    <div className="flex items-center gap-2">
                                        <span className="text-[10px] font-black text-[#afff34] bg-[#afff34]/10 px-2 py-0.5 rounded uppercase tracking-widest italic">
                                            {save.state.player.score} - {save.state.opponent.score}
                                        </span>
                                        <span className="text-xs font-black text-white/80 uppercase">
                                            {save.state.player.teamName} <span className="text-white/20 px-1">VS</span> {save.state.opponent.teamName}
                                        </span>
                                    </div>
                                    <span className="text-[9px] text-white/20 font-medium uppercase tracking-wider">{formatDate(save.timestamp)}</span>
                                </div>

                                <div className="flex gap-2">
                                    <button 
                                        onClick={() => copyLogs(save)}
                                        className={`p-3 rounded-xl transition-all active:scale-90 flex items-center gap-2 border border-white/5 ${copiedId === save.id ? 'bg-green-500/20 text-green-500 border-green-500/50' : 'bg-white/5 text-white/40 hover:text-white hover:bg-white/10'}`}
                                        title={t('game.copy_logs')}
                                    >
                                        {copiedId === save.id ? <MdCheck size={18} /> : <MdContentCopy size={18} />}
                                    </button>
                                    <button 
                                        onClick={() => deleteSave(save.id)}
                                        className="p-3 rounded-xl bg-red-500/10 text-red-500/40 border border-red-500/5 hover:bg-red-500/20 hover:text-red-500 transition-all active:scale-90"
                                    >
                                        <MdDelete size={18} />
                                    </button>
                                </div>
                            </div>

                            <button 
                                onClick={() => handleLoad(save.id)}
                                className="w-full py-3 rounded-xl bg-[#afff34] text-black font-black uppercase tracking-widest text-[11px] flex items-center justify-center gap-2 hover:bg-[#cfff70] active:scale-95 transition-all shadow-[0_5px_15px_rgba(175,255,52,0.2)]"
                            >
                                <MdPlayArrow size={20} />
                                {t('game.continue')}
                            </button>
                        </motion.div>
                    ))}
                </AnimatePresence>
            </div>
        )}
      </div>
    </motion.div>
  );
};

export default SavesScreen;